name: 'Terraform Check'

on:
  pull_request:

jobs:
  terraform-check:
    name: 'Terraform Check'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_stage: $${{ secrets.STAGE }}

    strategy:
      matrix:
        env: [ dev, staging, prod ]
    #environment: ${{ matrix.env }}

    steps:

      # Checkout project
      - name: Checkout Project
        uses: actions/checkout@v2
        id: p_checkout

      # Setup terraform action here
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
        id: tf_setup

      # Initialize terraform
      - name: Terraform Init
        run: terraform init -no-color
        id: tf_init

      # Do a terraform plan
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        id: tf_plan
